## Lab 6: Naive Bayes Text Classification

# News Classifiction

The 20 newsgroups dataset comprises around 18000 newsgroups posts on 20 topics split in two subsets: one for training (or development) and the other one for testing (or for performance evaluation). The split between the train and test set is based upon a messages posted before and after a specific date.

The news are from each of the following 20 newsgroups.

    alt.atheism
    comp.graphics
    comp.os.ms-windows.misc
    comp.sys.ibm.pc.hardware
    comp.sys.mac.hardware
    comp.windows.x
    misc.forsale
    rec.autos
    rec.motorcycles
    rec.sport.baseball
    rec.sport.hockey
    sci.crypt
    sci.electronics
    sci.med
    sci.space
    soc.religion.christian
    talk.politics.guns
    talk.politics.mideast
    talk.politics.misc
    talk.religion.misc

In [3]:
#import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#import 20 news group dataset from scikit learn datasets
from sklearn.datasets import fetch_20newsgroups

In [28]:
#The sklearn.datasets.fetch_20newsgroups function is a data fetching / caching
#functions that downloads the data archive from the original 20 newsgroups 
#website, extracts the archive contents in the ~/scikit_learn_data/20news_home 
#folder and calls the sklearn.datasets.load_files on either the training or 
#testing set folder.

#load 20 news group train subset - You need Internet for it/Or place the data file in Anaconda directory
newsgroups_train = fetch_20newsgroups(subset='train', shuffle=True)
#load 20 news group test subset
newsgroups_test = fetch_20newsgroups(subset='test', shuffle=True)

In [29]:
# print all target labels - dataset.target_names

dataset=newsgroups_train.target_names
print(dataset)
print(newsgroups_test.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [30]:
altatheism=dataset[0]
print(altatheism)
#print(newsgroups_train.target)
#newsgroups_train.data

alt.atheism


In [31]:
#prepare a list of categories 'alt.atheism', 'comp.graphics','sci.space'
classes = ['alt.atheism','comp.graphics','sci.space']
#newsgroups_train = fetch_20newsgroups(subset='train', categories=classes)
#from collections import Counter
#Counter([classes[t] for t in newsgroups_train.target])
classes

In [37]:
#load 20 news group train subset with three categories 'alt.atheism', 
#'comp.graphics','sci.space' by passing the list to fetch_20newsgroups 
#newsgroups_train = fetch_20newsgroups(subset='train', categories=catlist)
catlist_train=['alt.atheism','comp.graphics','sci.space']
newsgroups_train=fetch_20newsgroups(subset='train',categories=catlist_train)
#newsgroups_train.target_names
#load 20 news group test subset with three categories 'alt.atheism', 
#'comp.graphics','sci.space' by passing the list to fetch_20newsgroups 
catlist_test=['alt.atheism','comp.graphics','sci.space']
newsgroups_test=fetch_20newsgroups(subset='test',categories=catlist_test)


In [40]:
# print new training set target names(labels)
print(newsgroups_train.target_names)
print(newsgroups_test.target_names)

['alt.atheism', 'comp.graphics', 'sci.space']
['alt.atheism', 'comp.graphics', 'sci.space']


In [44]:
# print shape of targets
newsgroups_train.target.shape

(1657,)

In [45]:
#print training set filenames - dataset.filenames
print(newsgroups_train.filenames)
print(newsgroups_test.filenames)


['/home/naveen/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60869'
 '/home/naveen/scikit_learn_data/20news_home/20news-bydate-train/comp.graphics/38633'
 '/home/naveen/scikit_learn_data/20news_home/20news-bydate-train/alt.atheism/53534'
 ...
 '/home/naveen/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60915'
 '/home/naveen/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60176'
 '/home/naveen/scikit_learn_data/20news_home/20news-bydate-train/sci.space/60929']
['/home/naveen/scikit_learn_data/20news_home/20news-bydate-test/sci.space/61478'
 '/home/naveen/scikit_learn_data/20news_home/20news-bydate-test/comp.graphics/39046'
 '/home/naveen/scikit_learn_data/20news_home/20news-bydate-test/comp.graphics/39631'
 ...
 '/home/naveen/scikit_learn_data/20news_home/20news-bydate-test/alt.atheism/53598'
 '/home/naveen/scikit_learn_data/20news_home/20news-bydate-test/comp.graphics/38995'
 '/home/naveen/scikit_learn_data/20news_home/20news-bydate-test/sci.spac

In [54]:
# print new training data of 6th article - use dataet.data[index]

print(newsgroups_train.data[6])

From: cobb@alexia.lis.uiuc.edu (Mike Cobb)
Subject: Christian Morality is
Organization: University of Illinois at Urbana
Lines: 51

In <11836@vice.ICO.TEK.COM> bobbe@vice.ICO.TEK.COM (Robert Beauchaine) writes:

>In article <C5L1Ey.Jts@news.cso.uiuc.edu> cobb@alexia.lis.uiuc.edu (Mike 
Cobb) writes:
>>In <11825@vice.ICO.TEK.COM> bobbe@vice.ICO.TEK.COM (Robert Beauchaine) 
writes:
>>
>>
>>>  Actually, my atheism is based on ignorance.  Ignorance of the
>>>  existence of any god.  Don't fall into the "atheists don't believe
>>>  because of their pride" mistake.
>>
>>How do you know it's based on ignorance, couldn't that be wrong? Why would it
>>be wrong 
>>to fall into the trap that you mentioned? 
>>

>  If I'm wrong, god is free at any time to correct my mistake.  That
>  he continues not to do so, while supposedly proclaiming his
>  undying love for my eternal soul, speaks volumes.

What are the volumes that it speaks besides the fact that he leaves your 
choices up to you?

>  As for

In [108]:
#by using countvectorizer convert train data into numeric format considering only 1500 features
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(max_features = 1500)
vectors = count_vect.fit_transform(newsgroups_train.data)
vectors = vectors.toarray()
#print(vectors)
#print(vectors.shape)
print(vectors[5][1000:1004])

[0 0 0 0]


In [53]:
# use MultinomialNB(alpha=.01) for training - alpha is Laplace Smoothing 
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [109]:
#by using countvectorizer convert test data into numeric format considering only 1500 features
#count_vect_test=CountVectorizer(max_features=1500)
#vectors_test = count_vect_test.fit_transform(newsgroups_test.data)
vectors_test = count_vect.transform(newsgroups_test.data)
vectors_test=vectors_test.toarray()
print(vectors_test.shape)

(1102, 1500)


In [110]:
#predict target labels for testing set
mnb.fit(vectors_test,newsgroups_test.target)
pred = mnb.predict(vectors_test)
print(pred)

[2 1 1 ... 0 1 2]


In [111]:
#find accuacy score on test set
from sklearn import metrics
#pred=pred.reshape(-1,1)
y_test=newsgroups_test.target
metrics.accuracy_score(y_test,pred)


0.956442831215971

In [101]:
metrics.confusion_matrix(y_test,pred)

array([[312,   1,   6],
       [  6, 374,   9],
       [  4,  15, 375]], dtype=int64)

In [112]:
# used TfidfVectorizer insted of ContVectorizer and use multinomialNB
#find test set accuracy

from sklearn.feature_extraction.text import TfidfVectorizer
count_vect = TfidfVectorizer(max_features = 1500)
vectors = count_vect.fit_transform(newsgroups_train.data)
vectors = vectors.toarray()



# use MultinomialNB(alpha=.01) for training - alpha is Laplace Smoothing 
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()

#by using countvectorizer convert test data into numeric format considering only 1500 features
#count_vect_test=TfidfVectorizer(max_features=1500)
vectors_test = count_vect.transform(newsgroups_test.data)
vectors_test=vectors_test.toarray()
#print(vectors_test.shape)


#predict target labels for testing set
mnb.fit(vectors_test,newsgroups_test.target)
pred = mnb.predict(vectors_test)
print(pred)


#find accuacy score on test set
from sklearn import metrics
#pred=pred.reshape(-1,1)
y_test=newsgroups_test.target
metrics.accuracy_score(y_test,pred)


[2 1 1 ... 0 1 2]


0.9682395644283122

In [113]:
#try with avoiding stopwords and repeat the same

# used TfidfVectorizer insted of ContVectorizer and use multinomialNB
#find test set accuracy

from sklearn.feature_extraction.text import TfidfVectorizer
count_vect = TfidfVectorizer(max_features = 1500,stop_words='english')
vectors = count_vect.fit_transform(newsgroups_train.data)
vectors = vectors.toarray()



# use MultinomialNB(alpha=.01) for training - alpha is Laplace Smoothing 
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()

#by using countvectorizer convert test data into numeric format considering only 1500 features
#count_vect_test=TfidfVectorizer(max_features=1500,stop_words='english')
vectors_test = count_vect.transform(newsgroups_test.data)
vectors_test=vectors_test.toarray()
#print(vectors_test.shape)


#predict target labels for testing set
mnb.fit(vectors_test,newsgroups_test.target)
pred = mnb.predict(vectors_test)
print(pred)


#find accuacy score on test set
from sklearn import metrics
#pred=pred.reshape(-1,1)
y_test=newsgroups_test.target
metrics.accuracy_score(y_test,pred)









[2 1 1 ... 0 1 2]


0.9745916515426497

In [ ]:
#Extra - try grid search for count vectorizer, tfidf, different classifiers 

In [ ]:
#Extra - try with stemming also